# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml --project=[CICD_PROJECT]
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/prj-factory', '.']
- name: 'gcr.io/${PROJECT_ID}/prj-factory'
  args: ['-V']
images: ['gcr.io/${PROJECT_ID}/prj-factory']
